### ISSUE TITLE
CCL 3.2.1 release

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-ccl#100]
CCL Version 3.2.1 is showing on Android devices with CWA 2.25.0 or CWA 2.26.0 installed, so:

- [v3.2.1](https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v3.2.1) should be marked as latest and
- [v3.2.1](https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v3.2.1) should be merged into the [main](https://github.com/corona-warn-app/cwa-app-ccl/tree/main) branch

**Comment by MikeMcC399** [comment]
@mlenkeit 

Please check this when you have an opportunity!

**Comment by mlenkeit** [comment]
@MikeMcC399 thanks for the hint, it's done now, see https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v3.2.1.

**Comment by mlenkeit** [comment]
@MikeMcC399  you're right, done with https://github.com/corona-warn-app/cwa-app-ccl/commit/8b16bf9fe0061f4e04949f42f4af2e74468d3bd5
