### ISSUE TITLE
Deactivate push notification for status change (no status badge) with CCL?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#118]
CWA pushes notifications to the user reg. news from the app only to tell the user that the status badge is not shown anymore. In my opinion that's really unnecessary and should be deactivated if possible.

@mlenkeit

**Comment by Ein-Tim** [comment]
FYI: There seems to be confusion about the text, see e.g. https://twitter.com/ventil2110/status/1575113019482570752?s=46&t=WG5R2p9FI21akLwTqUW6Tg

**Comment by mlenkeit** [comment]
> CWA pushes notifications to the user reg. news from the app only to tell the user that the status badge is not shown anymore. In my opinion that's really unnecessary and should be deactivated if possible.
> 
> @mlenkeit

@Ein-Tim it's a one-time notification and will not show up again, unless something such as the G-status is re-introduced and displayed in CWA. It was a deliberate decision to notify users to avoid confusion around why the status badge with 2G, 2G+, etc. is suddenly not displayed anymore.

> FYI: There seems to be confusion about the text, see e.g. https://twitter.com/ventil2110/status/1575113019482570752?s=46&t=WG5R2p9FI21akLwTqUW6Tg

@Ein-Tim thanks for referencing the tweet! Are you aware of more such reports?

**Comment by Ein-Tim** [comment]
@mlenkeit

> Are you aware of more such reports?

Yes, here's one more: 
https://twitter.com/kaygiza/status/1575360014415499264?s=46&t=xR3_-SYKH5398Xpmt7kgvQ

**Comment by Ein-Tim** [comment]
See also:

- https://twitter.com/toni_auspuh/status/1575107475388661761?s=46&t=xR3_-SYKH5398Xpmt7kgvQ
- https://twitter.com/johl/status/1575106740516884480?s=46&t=xR3_-SYKH5398Xpmt7kgvQ

**Comment by Ein-Tim** [comment]
> it's a one-time notification and will not show up again, unless something such as the G-status is re-introduced and displayed in CWA. It was a deliberate decision to notify users to avoid confusion around why the status badge with 2G, 2G+, etc. is suddenly not displayed anymore.

OK, just for the future: I strongly suggest to not send push notifications for such news, see also the feedback from users on Twitter:
- https://twitter.com/farbenstau/status/1575366406585073664?s=46&t=xR3_-SYKH5398Xpmt7kgvQ
- https://twitter.com/thomasmechen/status/1575093653264949248?s=46&t=xR3_-SYKH5398Xpmt7kgvQ

**Comment by Ein-Tim** [comment]
I will close this issue and we can continue the discussion reg. the wording in #119.

**Comment by Ein-Tim** [comment]
@mlenkeit 

I want to elaborate a bit more to make you (and the team) understand why I and some other CWA users see this as a bad decision.
The status proof was a feature only CWA had, CovPass did never show the status this easy and clearly. So this was a USP of CWA which was now removed. With neither certificates relevant at the moment, nor check-ins, nor the contact journal, I, and others, see CWA loosing more and more their reason for existence.
For sure, there's still the exposure logging part of the app, but we all know that it meanwhile also lost importance. One of the last remaining top features of CWA is the test result transmission, which is great but would need expanding soon (make it possible to register rapid PCR tests, some way to register positive self tests, etc.).

Pushing to the user a notification which basically said "We removed another USP of the app", is not the best decision you can make if you want users to keep on using the app.
I am quite sure that there were quite a few users who thought, ah, ok I kept the CWA for my certificates but now the app tells me this is not relevant anymore (the key take-away of the text which is now displayed is that something reg. certificates is not relevant anymore) so I can also delete the app now.

So, this just for your understanding, that's not an attack and I'm very sure that you know about the problems of the app & you would like to change things up, but I also know that this is a highly political project and in the end it's not the team which makes the decisions here but some people at the BMG/RKI.

**Comment by mlenkeit** [comment]
@Ein-Tim thank you for elaborating, it's always good to get an outside view on things like this 👍

**Comment by mlenkeit** [comment]
@Ein-Tim thank you for elaborating, it's always good to get an outside view on things like this 👍

**Comment by Ein-Tim** [comment]
@mlenkeit I'm always happy to be of help. I'll let the topic rest for now, what happened has happened and I hope we all learn from it.

Thank you for your never-ending work with the community. I highly appreciate it!
