### ISSUE TITLE
Confusing wording reg. status removal

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#119]
There seems to be confusion going on reg. the removal of the status, see e.g. these Tweets:

- https://twitter.com/ventil2110/status/1575113019482570752?s=46&t=WG5R2p9FI21akLwTqUW6Tg
- https://twitter.com/toni_auspuh/status/1575107475388661761?s=46&t=xR3_-SYKH5398Xpmt7kgvQ
- https://twitter.com/johl/status/1575106740516884480?s=46&t=xR3_-SYKH5398Xpmt7kgvQ
- https://twitter.com/theglowingdice/status/1575390757984378880?s=46&t=xR3_-SYKH5398Xpmt7kgvQ

**Comment by Ein-Tim** [comment]
One more:
- https://twitter.com/sneaky_demi/status/1576438342992154625?s=46&t=CgW4Akp_2y_G7mwVAqDQBg

**Comment by GisoSchroederSAP** [comment]
Meanwhile, I double-checked the above-mentioned and many other twitter comments and emails regarding the "essence" of the confusion - sorry guys, there is no core. As much as I like the funny parts of those comments: There is a lot of irony, the usual snobbish comments, and phrasemongering. 
While we certainly need to explain the disappearance of a former UI element (so, suppression of the G status notice is not an option), I don't see a chance to provide a generic solution for this variety of user comments. From what I read, it's not really _confusion_ or understanding - but it looks like these users didn't actively realize, the G status is gone.
And thanks to @Ein-Tim most of the twitter comments are already answered, right?

So: What exactly is the "confusing wording"? Do we still have an open taks?

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Thanks for checking!

I think, and that was my main takeaway of the comments, is that users are misunderstanding the notification in a way they think their certificates in whole are irrelevant now, although only the status is irrelevant. However, I don't think this is a problem with the users not understanding the info text but just not correctly reading it. And we can't do anything about that.

I'm closing this issue.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Yes, I absolutely agree with you here, there is neither enough information where exactly the confusion is nor how we could improve it.
