### ISSUE TITLE
Deprecation warnings in Actions

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-ccl#126]
There are several deprecation warnings in the logs on https://github.com/corona-warn-app/cwa-app-ccl/actions, for example in https://github.com/corona-warn-app/cwa-app-ccl/actions/runs/3321051924

"Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, richardsimko/update-tag, softprops/action-gh-release, actions/checkout"

"The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"

If left unadressed they may lead to workflow failures in the future.

**Comment by brianebeling** [comment]
Thank you @MikeMcC399 

I addressed the issue similar to how we did it in the cwa-website repo already. Let me know if you see anything concerning, but that should fix the issue long term.

**Comment by mlenkeit** [comment]
@MikeMcC399 thanks for spotting the deprecation warnings!

I'm a bit surprised to see them though. The workflows are already using Node.js 16, see e.g. https://github.com/corona-warn-app/cwa-app-ccl/actions/runs/3321051924/jobs/5488178995#step:3:7.

Same applies to `set-output` - as far as I can tell, we are not using this feature in any of the workflows.

**Comment by MikeMcC399** [comment]
@mlenkeit 

This is about old versions of actions which call up Node.js 12 / set-output, so these calls are hidden.

See the error message, which says:

"Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, richardsimko/update-tag, softprops/action-gh-release, actions/checkout".

**Comment by MikeMcC399** [comment]
- See also https://github.com/softprops/action-gh-release/issues/249. You may need to look for alternatives to [softprops/action-gh-release](https://github.com/softprops/action-gh-release) if this action is not updated by its maintainer(s).

**Comment by MikeMcC399** [comment]
[softprops/action-gh-release](https://github.com/softprops/action-gh-release) has been updated to [v0.1.15](https://github.com/softprops/action-gh-release/releases/tag/v0.1.15).  [v1](https://github.com/softprops/action-gh-release/releases/tag/v1) is also tagged to the commit of [v0.1.15](https://github.com/softprops/action-gh-release/releases/tag/v0.1.15) so there is no change needed in [.github/workflows/release.yml](https://github.com/corona-warn-app/cwa-app-ccl/blob/main/.github/workflows/release.yml) for [softprops/action-gh-release](https://github.com/softprops/action-gh-release) in the following:

https://github.com/corona-warn-app/cwa-app-ccl/blob/db3bae496808c9c3b6e00fa4b7a508a1d4901f1b/.github/workflows/release.yml#L47-L54

**Comment by MikeMcC399** [comment]
@mlenkeit 

I was a bit confused about why some of the deprecation warnings are still showing.

You might need to provide the [release/3.5.x](https://github.com/corona-warn-app/cwa-app-ccl/tree/release/3.5.x) branch to the fork https://github.com/service-tip-git/cwa-app-ccl.

The issue with the action [richardsimko/update-tag@v1](https://github.com/richardsimko/update-tag) should be fixed now and should not show up in the log for ci.yml the next time it is run.

**Comment by MikeMcC399** [comment]
https://github.com/corona-warn-app/cwa-app-ccl/actions/runs/3631704540 looks fine now which is the latest action log in https://github.com/corona-warn-app/cwa-app-ccl/actions?query=branch%3Arelease%2F3.5.x. So the deprecation issue is fixed.
