### ISSUE TITLE
Release 3.5.1?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-ccl#132]
@mlenkeit 

I don't see any CCL 3.5.1 release although CWA 3.0 is showing that it is using this version of CCL.

Will you release 3.5.1 in this repo and merge into `main`?

---
Internal Tracking ID: [EXPOSUREAPP-14702](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14702)

**Comment by MikeMcC399** [comment]
Is this repository still being maintained?

The latest release is [v3.4.0](https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v3.4.0).

Branch [3.5.x](https://github.com/corona-warn-app/cwa-app-ccl/compare/main...release/3.5.x) is 15 commits ahead of `main` and the current app (Android 3.0.1) is showing CCL Version: 3.5.1.

**Comment by Ein-Tim** [comment]
Ping @mlenkeit, as he maintained this repository in the past.

**Comment by Ein-Tim** [comment]
Also adding @dsarkar & @larswmh here. Could you please make sure this repository continues to be maintained?

**Comment by mlenkeit** [comment]
@MikeMcC399  @Ein-Tim  thanks for bringing this to our attention, releases have been updated.

**Comment by MikeMcC399** [comment]
@mlenkeit 

You probably need to tag https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v3.5.1 as `latest`, as it otherwise doesn't show up on the main page.

You also have a tag https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/latest. You might like to check if that is intended to be there.

**Comment by MikeMcC399** [comment]
![image](https://user-images.githubusercontent.com/66998419/217322149-d35a284b-c488-4115-bfdc-2e81d53239ac.png)

**Comment by dsarkar** [comment]
@MikeMcC399 label was changed to latest for v3.5.1.
