### ISSUE TITLE
Is version 3.6 already in rollout?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#137]
My CWA currently shows CCL version 3.5.1 as the version that's currently used, and I'm wondering when version 3.6 will actually be deployed, as it contains time-sensitive changes (for tomorrow).

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Would you expect a blog article publication for such a major change?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Not certainly a blog post. I was just wondering, because I understand the changes in https://github.com/corona-warn-app/cwa-app-ccl/commit/ee6fc12cbafec2b45f6b913580cff31c20ab7ab1 so that it was intended to show the notice starting today at 00:00h, but not it is 11:00h and I'm still not seeing any notice, what only makes sense as CCL version 3.5.1 is still the version used by CWA on my phone, but the change is in version 3.6.

**Comment by MikeMcC399** [comment]
- https://github.com/corona-warn-app/cwa-website/pull/3444 has just been published

**Comment by Ein-Tim** [comment]
My device now shows version 3.6 of CCL as installed, @mlenkeit could you release that version here on GitHub too?

Thanks!

**Comment by MikeMcC399** [comment]
@mlenkeit 

Please merge 3.6 into main!

(GitHub is however currently experiencing problems. See https://www.githubstatus.com/.)
