### ISSUE TITLE
v3.6.0 version maintenance

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-ccl#138]
1. Please mark [v3.6.0](https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v3.6.0) as latest (instead of pre-release).
2. Please also merge [release/3.6.x](https://github.com/corona-warn-app/cwa-app-ccl/tree/release/3.6.x) into [main](https://github.com/corona-warn-app/cwa-app-ccl/tree/main)

- [x] I have submitted https://github.com/corona-warn-app/cwa-website/pull/3447 

---
Internal Tracking ID: [EXPOSUREAPP-15006](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15006)

**Comment by MikeMcC399** [comment]
@mlenkeit are you still involved in this?

**Comment by Ein-Tim** [comment]
cc'ing @larswmh & @brianebeling here

**Comment by mlenkeit** [comment]
@MikeMcC399  thanks for bringing this up. I've updated the latest release, see https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v3.6.0.

**Comment by MikeMcC399** [comment]
@mlenkeit 

> I've updated the latest release, see https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v3.6.0.

Thank you!

Do you also plan to merge the branch [release/3.6.x](https://github.com/corona-warn-app/cwa-app-ccl/tree/release/3.6.x) into the [main](https://github.com/corona-warn-app/cwa-app-ccl/tree/main) branch?

![image](https://user-images.githubusercontent.com/66998419/229087504-20bf59a6-baf7-41ee-b5d5-339256170acc.png)
