### ISSUE TITLE
Merge version 3.6.0 branch into `main`

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#140]
Please, as @MikeMcC399 already requested back in #138, merge https://github.com/corona-warn-app/cwa-app-ccl/tree/release/3.6.x into https://github.com/corona-warn-app/cwa-app-ccl/tree/main.

---
Internal Tracking ID: [EXPOSUREAPP-15006](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15006)

**Comment by MikeMcC399** [comment]
Nothing happened on this so far.

**Comment by Ein-Tim** [comment]
Pinging @mlenkeit here one more time.

**Comment by Ein-Tim** [comment]
@larswmh Please take a look here

**Comment by larswmh** [comment]
@Ein-Tim @MikeMcC399 I've brought this up again internally, please stand by
