### ISSUE TITLE
CWA shows 1.0.0-rc.7 as currently used CCL version

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#33]
### This is an informational issue

See title. I guess you intended to show 1.0.0, see https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v1.0.0.

**Comment by mlenkeit** [comment]
@Ein-Tim thanks for raising this. Technically, v1.0.0 and v1.0.0-rc.7 contain exactly the same code. The RC build is currently live on production due to the initial go-live of the feature and some internal beta testing prior to that. We shouldn't see this again in the future.

**Comment by Ein-Tim** [comment]
Okay, as this is just a minor issue and I expect a fix soon, I'm already closing this issue now.

**Comment by Ein-Tim** [comment]
@mlenkeit CWA still shows the RC in the version. Is this your intention?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Are you referring to the version display in the released version of the app?

In Android, three-dot symbol > App Information

![image](https://user-images.githubusercontent.com/66998419/155720673-9b5614b8-edbf-4094-82b1-a81be5ffc37d.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399

Yes, I do.

**Comment by mlenkeit** [comment]
> @mlenkeit CWA still shows the RC in the version. Is this your intention?

@Ein-Tim yes, it should disappear latest with CWA 2.19.

**Comment by MikeMcC399** [comment]
CCL Version is now 1.1.0 even if CWA Android 2.18.1 is still installed. I know this issue is closed, but it really is resolved now.
