### ISSUE TITLE
Is it intended that a 2/1 certificate only shows 2G and not 2G+?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#44]
I have a user on Twitter with the following case:
1. Recovered in March 2021
2. Vaccinated with J&J in in June (1/1)
3. Boostered with Biontech in November (2/1)

Only the 2G status is shown, although the 2/1 certificate is clearly identifiable as a booster vaccination.

Is this intended? Am I missing something?

**Comment by Skeeve** [comment]
Here is the user waiting ;)

**Comment by thomasaugsten** [comment]
I cannot reproduce this situation.
Can you please explain when you receive the 2/1 certificate?

![image](https://user-images.githubusercontent.com/6367738/157216074-d55eea02-66cb-4dda-b18c-3bb76e6751b6.png)

**Comment by Skeeve** [comment]
That seems to be the issue: I have no scanable "Genesenenzertifikat" and there seems to be no way for anyone to create one for me :( I simply only received a QR Code of my local Gesundheitsamt and that's not scanable by the App. The Pharmacy can only create certificates for up to 180 days back and mine is about 360 days back.

**Comment by thomasaugsten** [comment]
Questions regarding creation of certificate please approach the certificate team directly
support@covpass-app.de
Impfnachweis@rki.de

**Comment by Ein-Tim** [comment]
@thomasaugsten So it is intended that a 2/1 certificate alone does not yiel the 2G+ status?

**Comment by thomasaugsten** [comment]
Only in combination with a 1/1 J&J vaccination

**Comment by Ein-Tim** [comment]
@thomasaugsten And exactly this is the case for @Skeeve or am I mistaken?

**Comment by Skeeve** [comment]
I don't get it. Sorry.

So J&J + Biontech != Booster?

But "Genesen" + J&J + Biontech == Booster?

And the only issue for me ist the missing "Genesenen"?

**Comment by MikeMcC399** [comment]
@Skeeve 

> That seems to be the issue: I have no scanable "Genesenenzertifikat" and there seems to be no way for anyone to create one for me :( I simply only received a QR Code of my local Gesundheitsamt and that's not scanable by the App. The Pharmacy can only create certificates for up to 180 days back and mine is about 360 days back.

Your recovery one year ago in March 2021 is no longer relevant.

According to https://www.coronawarn.app/en/faq/#eu_dcc_validity Certificates of Recovery are only valid for 90 days (although there are some legal discussions about whether the original 180 days should still count). You said yourself, "mine is about 360 days back", so even if the 180 day-rule were used, your recovery about one year ago no longer counts. You should just forget about this point.

**Comment by Skeeve** [comment]
> @Skeeve
> Your recovery one year ago in March 2021 is no longer relevant.

So then please explain

1. The screenshot above
2. This from https://www.coronawarn.app/de/blog/2022-02-23-cwa-2-18/ :

> „Aufgefrischt“ (geboostert) bedeutet: (a) Grundimmunisiert und Auffrischimpfung erhalten (gilt sofort) oder (b) Genesen und danach mindestens zwei Impfungen erhalten (gilt sofort bzw. ab Tag 15 mit einem 2/1-Zertifikat) oder (c) Vollständig geimpft und genesen (ab Tag 29 nach positivem PCR-Testergebnis). Der 2G+-Status ist zeitlich unbegrenzt.

**Comment by thomasaugsten** [comment]
This is not correct for the G Status the recovery is important to determine the state in the CWA independent how old the recovery is.
For example a recovery before or after a Grundimmunisierung leads to an infinite valid 2G+ state

**Comment by Ein-Tim** [comment]
> So J&J + Biontech != Booster?

Exactly, because the Biontech shot is only the end of the basic immunisation.

> And the only issue for me ist the missing "Genesenen"?

Yep.

@thomasaugsten What is the recommendation from the CWA team in this situation?

**Comment by thomasaugsten** [comment]
The CWA is able to scan expired certificates

**Comment by Ein-Tim** [comment]
@thomasaugsten But what is the recommendation from the CWA Team in this case? Pharmacies can't issue already expired certificates.

**Comment by thomasaugsten** [comment]
As I said we cannot give recommendation from our side. Please contact the certificate teams to find a solution or to change the current situation

[support@covpass-app.de](mailto:support@covpass-app.de)
[Impfnachweis@rki.de](mailto:Impfnachweis@rki.de)

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay.
@Skeeve Will you do this? If so, please keep me posted via Twitter DM.

I'll close this issue now as not fixable from CWA side.

**Comment by Skeeve** [comment]
I already wrote a mail to both addresses. Regarding the QR code: It‘s one which is incompatible to the app, not because it‘s expired.

**Comment by vaubaehn** [comment]
@thomasaugsten 
> The CWA is able to scan expired certificates

Thank you, this is helpful information to support users from our side.


@Skeeve 
> Regarding the QR code: It‘s one which is incompatible to the app, not because it‘s expired.

Thanks for clarification. I hope you'll find a good solution for your situation. Please keep us updated!

**Comment by Skeeve** [comment]
@vaubaehn 

> Thanks for clarification. I hope you'll find a good solution for your situation. Please keep us updated!

I fear this will be difficult to impossible as the standard software pharmacies use has the 180day limit. I think someone who can compile this software will have to create one ignoring the limit and then generate a certificate.

I also wrote to the Bundesgesundheitsministerium but I do not have much hope to get help.

**Comment by vaubaehn** [comment]
@Skeeve 

> I fear this will be difficult to impossible as the standard software pharmacies use has the 180day limit. I think someone who can compile this software will have to create one ignoring the limit and then generate a certificate.

Who may help here is Ubirch, who is the stakeholder repsonsible for the technical part of signing Digital Covid Certificates. They are providing their own technical solutions and are in touch with 3rd parties.
Please open an issue in https://github.com/Digitaler-Impfnachweis/certification-apis/ , describe your problem and ask them to initiate a communication with RKI/BMG regarding the issue. They may help to change certification APIs to issue also "old" recovery certificates. You may ping thinkberg from there as the lead architect.
Please ping me from there when you opened an issue, and - if he wants - also Ein-Tim.

**Comment by Skeeve** [comment]
Vielleicht sollte ich mich hier anschließen, @vaubaehn https://github.com/Digitaler-Impfnachweis/certification-apis/issues/228, oder?

**Comment by vaubaehn** [comment]
@Skeeve 
Ich würde tatsächlich ein neues Issue aufmachen. Nach allem, was ich jetzt nachvollziehen kann, brauchst du einfach das alte Genesenenzertifikat in digitaler DCC-Form in der Corona-Warn-App oder CovPassApp, wenn du nicht immer den "Genensenen"-Zettel vom Gesundheitsamt mit herumschleppen möchtest und bei Einlasskontrollen diskutieren willst... Und das Thema ist noch ein bisschen anders gelagert/präziser, als das https://github.com/Digitaler-Impfnachweis/certification-apis/issues/228.

Ubirch hat zwar die Möglichkeiten, das technisch umzusetzen, dass auch Genensenenzertifikate ausgestellt werden können, wo der PCR-Test schon mehr als 180 Tage zurück liegt, aber es wird vermutlich dazu auch eine politische Entscheidung brauchen, dass solche Zertifikate ausgestellt werden dürfen. Vorher kann Ubirch da nichts machen. Aber: Sie könnten dazu eine Diskussion mit dem RKI bzw. dem BMG aufmachen, daher glaube ich, dass sie die richtigen Ansprechpartner sind, und wenn eine entsprechende Entscheidung gefallen ist, auch gleich an die Umsetzung gehen können.

Ich glaube sogar, dass es insgesamt recht viele Menschen betreffen kann, ohne jetzt auf konkrete Zahlen zurückgreifen zu können. Von daher glaube ich, könnte es für viele Betroffene hilfreich sein, wenn du den Stein ins Rollen bringst.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

I'm just thinking. Will it change anything if @Skeeve reissues their first vaccination certificate from "1 von 1" to "2 von 1" and gets a "3 von 1" certificate for the second vaccination? Will CCL then determine the 2G+-Status?

**Comment by thomasaugsten** [comment]
It is not possible to convert a 1/1 to a 2/1

**Comment by Skeeve** [comment]
But this wouldn't be legal @Ein-Tim, I fear. And, tbh. I wouldn't want them to do something illegal.

It would be sufficient would there exist a way to regenerate a lost, written certificate. Mine is, if you so will, a lost print and the only reason why would want to have it is to satisfy the conditions for the app to show me 2G+.

At the moment I have a photo of my "Gesundheitsamt"'s print with me. I hope it will satisfy any doorman should I ever need 2G+.

**Comment by Ein-Tim** [comment]
I don't think that's illegal it's just another Interpretation if the rules. 

We had discussed this before, e.g. here: https://github.com/corona-warn-app/cwa-app-android/pull/4764#issuecomment-1026924372

The EU is not very clear on what a 2/1 certificate is.

cc @vaubaehn

**Comment by Ein-Tim** [comment]
There's nothing left here the CWA team can do. Closing.
