### ISSUE TITLE
Always prefer vaccination certificates over recovery certificates if the recovery cert. is older than 90 days

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#49]
It seems like CWA currently prefers recovery certificates over vaccination certificates until 180 days have passed since the positive test.
This should be adjusted and CWA should only prefer recovery certificates for 90 days, else users with a valid 2G+ status (and a recovery which is valid 180 days (but CovPassCheck can't detect)) will be rejected because their certificate expired.

**Comment by Ein-Tim** [comment]
@mlenkeit 

There are multiple users on Twitter reporting that their status disappeared with the update to 2.19. 
In 2 cases the app merged vaccination & recovery certificates, now prefers the recovery certificate although it is older than 90 days and shows no status anymore.

This is IHMO a top priority issue. Could you please comment so that we know you are aware of this issue?

**Comment by thomasaugsten** [comment]
Can you please give details what vaccination are used. Is there no status or from 2G+ to 2G. A screenshot would be helpful.

**Comment by Ein-Tim** [comment]
@thomasaugsten I will ask the users however wouldn't the change I suggest in the OP make sense anyways?

**Comment by thomasaugsten** [comment]
I think CovPass will change the acceptance of recover certificate independent of the valid to date in the certificate

**Comment by Ein-Tim** [comment]
@thomasaugsten 

This is not the problem. Let me try to explain it again:

The user has a
- 1/2 vaccination certificate
- 2/2 vaccination certificate
- 1 recovery certificate 

in their app.

The app now prefers the recovery certificate for 180 days over the 2/2 certificate although the recovery certificate is only valid for 90 days.
This then results that when the user shows their certificate on the "Certificates Overview screen", as suggested by the app, CovPassCheck rejects the certificate as invalid, as it doesn't know that this is a recovery certificate after basic immunisation.

How to fix this?
Prefer a recovery certificate over other certificates only if the certificate isn't older than 90 days.

**Comment by thomasaugsten** [comment]
This is difficult because the recovery certificate is a proof for his 2G+ status. He has to show it manually until the covpass includes this in the 2G+ check.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Yeah but there are two options here
a) show a valid vaccination certificate
b) show an invalid recovery certificate

Do you really think it is better when the user shows an invalid recovery certificate (always, even if the person controlling is checking for 3G) then showing a valid vaccination certificate?

Keep in mind that most federal states are lifting their 2G+ restrictions.

**Comment by thomasaugsten** [comment]
Ok we will discuss this and update the ccl according to the decision

**Comment by mlenkeit** [comment]
@Ein-Tim will be covered by #55, release date is not yet decided.

**Comment by Ein-Tim** [comment]
@mlenkeit 

Trank you! I can't test this fix, though.
