### ISSUE TITLE
Rollout mechanism for CCL

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-ccl#62]
@mlenkeit 

I just re-installed CWA Android 2.19.2 on a test device and I am still seeing CCL Version: 1.2.1 (not 1.2.3). 

- Is the roll-out availability controlled on the server side?
- Would you expect a fresh install to see 1.2.1 at this time?

**Comment by mlenkeit** [comment]
@MikeMcC399 we had to revert the CLL update because it caused a problem on some devices. The current version live version is again 1.2.1.

**Comment by MikeMcC399** [comment]
@mlenkeit 

Thank you for keeping us up to date. Good luck with the fixes! 🙂
