### ISSUE TITLE
Twitter Report: DCC_RI_429 issue

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#69]
A user on version 2.20.3 (iOS) is trying to get their certificate reissued. However, she encounters the DCC_RI_429 error when attempting to perform the necessary steps. Here is a link to the Twitter report: https://twitter.com/UteLomberg/status/1511216624883412994?s=20&t=f40EqH_pHEM7rzaqJr5YLg

If you need any more information, please, let me know.

Would appreciate if you could assist here ASAP @thomasaugsten / @mlenkeit.

**Comment by thomasaugsten** [comment]
429 means maximal reissue limit of 3 is reached.
After 3 issuing the same certificate you have to scan reissued certificate to have it on mutiple devices

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Thanks Thomas, I asked her whether she already successfully reissued the certificate.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

The user answered that the reissuance was never successful. She talked to the technical hotline today and they mentioned a "ticket" with the ID "4791". No idea if they maybe refer to the JIRA EXPOSUREBACK-4791 ticket?
They also said that the issue is known. Is this true? 
The user is using an iPhone 12 Pro Max and her husband was able to get his certificate reissued today without problems.

**Comment by thomasaugsten** [comment]
This is an internal hotline ticket. The issue is "known" because the user will receive this after 3 reissuing.
The important question is here what happens in the first 3 attempts

**Comment by Ein-Tim** [comment]
@thomasaugsten You mean there maybe was another error? Does this also count into the "Rate Limit"?

Maybe she tried to reissue the certificate while the wrong URL was used in the app and thus she received the error I reported in #67?

**Comment by thomasaugsten** [comment]
No other error codes or wrong URL is not counting into the rate limit. 
A real certificates has to be generated to count into the rate limit.

**Comment by Ein-Tim** [comment]
Mh, okay. Strange. I asked here again if she is sure that there was never a successful reissuance, even not on another device.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

The user says that she never reissued the certificate successful, not even on another device.

Would you like to get in touch with her directly? If yes, I could give her your E-Mail address, but I don't want to share it w/o your consent.

**Comment by thomasaugsten** [comment]
Without an error log or a memory whats happens in the first 3 attempts we cannot help here

**Comment by Ein-Tim** [comment]
Ok I suggested to get the certificates reissued via an pharmacy.

Maybe it would make sense to include a helpful error message and not just some random error code which does not help the user?
