### ISSUE TITLE
On which basis were the status badge rules decided? 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#74]
## Your question

I'm asking myself the question which basis was used for the status badges. So to be concrete, e.g.: Who defined that 2G+ is also always shown for 90 days after a recovery, etc. Did the RKI just decide that these are the rules it wants and ignored that they might not be in touch with the reality? Or did the team look up what the most similarities throughout the federal regulations were and then implemented it like this.

Why I'm asking this: 2G+ is not used anymore in most federal states, but in Hamburg & Mecklenburg Vorpommern. Even these two federal states defined the 2G+ status different from another. So even at this date CWA does not show the correct rules in all federal states. 

---
Internal Tracking ID: [EXPOSUREAPP-12899](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12899)

**Comment by Ein-Tim** [comment]
Okay update: MV will have to stop using 2G/2G+/3G, see https://www.ndr.de/nachrichten/mecklenburg-vorpommern/Corona-Gericht-kippt-flaechendeckende-Hotspot-Regelung-in-MV,coronavirus6634.html

**Comment by GisoSchroederSAP** [comment]
The rule table for the G status determination was developed based on an in-depth comparison of the individual regulations of all 16 federal states. The federal states followed the recommendations of the RKI, PEI and WHO scientists and as well the regional political and legal considerations.
Out of the comparison results, the Federal Ministry of Health has prepared the national recommendation for the "conversion" of different scenarios to 3G, 2G, 2G plus status - this recommendation is implemented in the Corona War  App.
Beside the fact that many feredal states and districts have lifted local restrictions, this prepared recommendation is often used for guidance and communication. 
Still, as it is impossible to merge the regulations of all federal states into one rule set, in the [CWA FAQ](https://www.coronawarn.app/en/faq/results/#admission_policy_2gplus) we already point out: 

> For local interpretation and, if necessary, time limits, please contact the authorities of the respective federal state.

Please note that the 90-day rule is based on the scientific evidence that  in time, unfortunately, the "recovered" status provides only quite limited protection against reinfection or severe disease progression of COVID-19, especially with the observed  immune escape tendency of new virus variants.

I hope, this answers the question.

**Comment by Ein-Tim** [comment]
It does @GisoSchroederSAP! Thank you very much!
