### ISSUE TITLE
Is CCL/CWA ready to deal with 1/1 vaccinations for children?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ccl#83]
[STIKO recommends](https://www.rki.de/DE/Content/Kommissionen/STIKO/Empfehlungen/PM_2022-05-24.html) that children between 5-11 are vaccinated one time.
This will most likely result in a 1/1 certificate. Is CCL/CWA ready to deal with these certificates? Because I think currently, CWA always assumes that a 1/1 certificate (but a 1/1 certificate of J&J) is a certificate of one vaccination after recovery.

**Comment by DerVogel2020** [comment]
And what about the children in the age of 11 with a 1/1 certificate celebrating their 12th birthday. Will the 1/1 certificate automatically turn to a 1/2 inside the app?

**Comment by Ein-Tim** [comment]
@DerVogel2020 Thanks for adding this! As the birthday is included in the certificate, the app should know that that's a vaccination for children. When they turn 12, the app should automatically add a booster recommendation.

**Comment by Ein-Tim** [comment]
Huhu, @mlenkeit, this is a real world problem: https://twitter.com/tempobolzer/status/1535125138852745216?s=21&t=SjuVCVy6zyCa6Tq03X5lpw

Maybe you could comment that the team is aware of this?

**Comment by mlenkeit** [comment]
@Ein-Tim thanks for raising this.

To our knowledge, children should still receive a 1/2 certificate in such cases.

Irrespective of this, the STIKO recommendation is currently not reflected in IfSG, e.g. [§ 22a](https://www.gesetze-im-internet.de/ifsg/__22a.html), where there is no distinction by age. There are ongoing discussion about this topic between all involved parties. Once there is an agreement, we may adopt it in CWA/CCL.

**Comment by Ein-Tim** [comment]
Hey @mlenkeit, do you have any updates for us? What is the situation in the CWA currently?

**Comment by mlenkeit** [comment]
To my knowledge IfSG (still) does not make any distinction based on age. With CCL, we intent to reflect IfSG and thus, we wouldn't have any special logic for children, either.
