### ISSUE TITLE
CCL Version 3.1.0 not merged into main

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-ccl#86]
Will the released CCL Version 3.1.0 from branch [release/3.1.x](https://github.com/corona-warn-app/cwa-app-ccl/tree/release/3.1.x) be merged into the [main](https://github.com/corona-warn-app/cwa-app-ccl/tree/main) branch?

**Comment by MikeMcC399** [comment]
The question is related to
- PR https://github.com/corona-warn-app/cwa-website/pull/3074

as initially I didn't realise that I had to look into the  [release/3.1.x](https://github.com/corona-warn-app/cwa-app-ccl/tree/release/3.1.x) branch to find the current `faqAnchor` links from CCL which I have added to the Cypress test making sure that all links which the app defines or uses and which target https://www.coronawarn.app are available and working.

**Comment by mlenkeit** [comment]
Thanks @MikeMcC399 for bringing this up, simply forgot to update `main`.
