### ISSUE TITLE
Suggestions for FAQ Link from Booster text for DE-BNR-0110

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-ccl#88]
## Where to find the issue

https://github.com/corona-warn-app/cwa-app-ccl/blob/97d66df83eb232824efe39db880b661c0c1b9e83/lib/ccl/functions/getDccWalletInfo.js#L461 defines the faqAnchor `vac_cert_booster` which displays in the CWA app as "For further information, please see our FAQ page." and links to the website https://www.coronawarn.app/en/faq/#vac_cert_booster.

## Describe the issues

1. There is a website issue logged as https://github.com/corona-warn-app/cwa-website/issues/3073 which causes a mobile device not to display FAQ booster information when the link is clicked on.

2. The anchor `#vac_cert_booster` no longer exists on the website. It was removed when the FAQs were reorganized and instead the anchor is redirected to `#vac_cert` according to https://github.com/corona-warn-app/cwa-website/blob/bc2485d70bab67b865a6aad08c69cfa3f3815bd0/src/data/faq_redirects.json#L9.

## Steps to reproduce

Mobile device is connected via WLAN

1. Tap Scan and scan in a 2/2 vaccination certificate
2. Tap back-arrow
3. Tap Certificates
4. Tap right-arrow
5. Tap "Note on Booster Vaccination"

![DE-BNR-0110](https://user-images.githubusercontent.com/66998419/184377712-096373e9-1a5e-4895-ba86-d11e6e683c6a.jpg)

6. Tap on link at bottom of text to Rule DE-BNR-0110 "For further information, please see our FAQ page."
7. Note that browser first goes to https://www.coronawarn.app/en/faq/#vac_cert_booster then to https://www.coronawarn.app/en/faq/results/#vac_cert. The display however shows only topic sections.

![image](https://user-images.githubusercontent.com/66998419/183151644-3408efe0-cdca-4156-b2de-0abf77156b05.png)

## Expectation

When using the link on a mobile device useful information related to the booster notice should be shown.

## Suggestions

The following are some alternatives:

1. Change the anchor `#vac_cert_booster` on CCL to point to the existing article with anchor `#vac_booster_basics`. The article is [What is a booster vaccination and how does it appear in the CWA?](https://www.coronawarn.app/en/faq/results/#vac_booster_basics) and it seems to fit the information needs for a reader of `DE-BNR-0110` most closely.

2. Write a new FAQ article related to `DE-BNR-0110`, give it a new anchor, publish it and change CCL accordingly.
3. Remove the anchor `#vac_cert_booster` from CCL.
4. Fix issue https://github.com/corona-warn-app/cwa-website/issues/3073. Make no changes in CCL.

---

EXPOSUREAPP-13805

**Comment by mlenkeit** [comment]
Thanks @MikeMcC399 for raising this, mirrored to Jira as EXPOSUREAPP-13805.

**Comment by MikeMcC399** [comment]
@mlenkeit 

Thank you for picking up the suggestion and putting it into PR #90! Is there a concrete plan at the moment for moving this into production? I can see [v3.2.0](https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v3.2.0) marked as pre-release.

**Comment by mlenkeit** [comment]
@MikeMcC399 it will most likely be released with CWA 2.26 towards the end of the month.

**Comment by MikeMcC399** [comment]
I noticed that the FAQ https://www.coronawarn.app/en/faq/results/#vac_booster_basics specifies a 3 month wait for a 1st booster vaccination, which is in alignment with the BNR rules but no longer in alignment with the 21st STIKO recommendations. I have logged:

- https://github.com/corona-warn-app/cwa-website/issues/3080 and
- https://github.com/corona-warn-app/dcc-rule-translation/issues/10

to clarify and make changes if necessary.

**Comment by MikeMcC399** [comment]
This change is implemented and live in CCL 3.2.1 in use by CWA 2.26.
